/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.masterclass;

import fullhouse.models.Masterclass;
import fullhouse.repositories.MasterclassDbRepository;

/**
 *
 * @author steve
 */
public class MasterclassTabsPanel extends javax.swing.JPanel {
    private final MasterclassDbRepository repository = new MasterclassDbRepository();
    
    /**
     * Creates new form MasterclassTabsPanel
     */
    public MasterclassTabsPanel(Masterclass masterclass) {
        initComponents();
        
        MasterclassFormPanel form = new MasterclassFormPanel(masterclass);
        masterclassTabs.addTab("Gegevens", form);
        masterclassTabs.addTab("Spelers inschrijven", new MasterclassSignUpPanel(masterclass));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterclassTabs = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterclassTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterclassTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane masterclassTabs;
    // End of variables declaration//GEN-END:variables
}
