/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.masterclass;

import fullhouse.Panel;

/**
 *
 * @author steve
 */
public class MasterclassPanel extends javax.swing.JPanel {
    private Panel panel = new Panel();
    /**
     * Creates new form MasterClassPanel
     */
    public MasterclassPanel() {
        initComponents();
        
        panel.initializeButtons(
                new javax.swing.JButton[] { addMasterclassButton, editMasterclassButton, deleteMasterclassButton },
                new javax.swing.JButton[] { cancelMasterclassButton, saveMasterclassButton }    
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelMasterclassButton = new javax.swing.JButton();
        deleteMasterclassButton = new javax.swing.JButton();
        addMasterclassButton = new javax.swing.JButton();
        editMasterclassButton = new javax.swing.JButton();
        saveMasterclassButton = new javax.swing.JButton();
        subPanel = new javax.swing.JPanel();

        cancelMasterclassButton.setText("Annuleer");
        cancelMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMasterclassButtonActionPerformed(evt);
            }
        });

        deleteMasterclassButton.setText("Verwijder masterclass");

        addMasterclassButton.setText("Voeg masterclass toe");
        addMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMasterclassButtonActionPerformed(evt);
            }
        });

        editMasterclassButton.setText("Wijzig masterclass");
        editMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMasterclassButtonActionPerformed(evt);
            }
        });

        saveMasterclassButton.setText("Opslaan");
        saveMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMasterclassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveMasterclassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelMasterclassButton)
                .addGap(0, 20, Short.MAX_VALUE))
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMasterclassButton)
                    .addComponent(editMasterclassButton)
                    .addComponent(deleteMasterclassButton)
                    .addComponent(saveMasterclassButton)
                    .addComponent(cancelMasterclassButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMasterclassButtonActionPerformed
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterClassFormPanel());
        panel.toForm();
    }//GEN-LAST:event_addMasterclassButtonActionPerformed

    private void editMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMasterclassButtonActionPerformed
        // TODO add your handling code here:
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterClassFormPanel());
        panel.toForm();
        
    }//GEN-LAST:event_editMasterclassButtonActionPerformed

    private void saveMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMasterclassButtonActionPerformed
        // TODO add your handling code here:
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterclassCollectionPanel());
        panel.toCollection();
    }//GEN-LAST:event_saveMasterclassButtonActionPerformed

    private void cancelMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMasterclassButtonActionPerformed
        // TODO add your handling code here:
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterclassCollectionPanel());
        panel.toCollection();
    }//GEN-LAST:event_cancelMasterclassButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMasterclassButton;
    private javax.swing.JButton cancelMasterclassButton;
    private javax.swing.JButton deleteMasterclassButton;
    private javax.swing.JButton editMasterclassButton;
    private javax.swing.JButton saveMasterclassButton;
    public javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}
