/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.masterclass;

import fullhouse.models.Masterclass;
import fullhouse.models.Player;
import fullhouse.repositories.MasterclassDbRepository;
import fullhouse.repositories.PlayerDbRepository;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author steve
 */
public class MasterclassFormPanel extends javax.swing.JPanel {

    private final MasterclassDbRepository masterclassRepo = new MasterclassDbRepository();
    private Masterclass masterclass;
    
    /**
     * Creates new form MasteclassFormPanel
     */
    public MasterclassFormPanel() {
        initComponents();
        populateLeaderBox();
    }
    
    public MasterclassFormPanel(Masterclass masterclass) {
        initComponents();
        populateLeaderBox();
        this.masterclass = masterclass;
        this.setValues();
    }
    
    public void populateLeaderBox() {
        PlayerDbRepository playerRepo = new PlayerDbRepository();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<Player> leaders = playerRepo.getLeaders();
        
        for(Player leader : leaders) {
            model.addElement(leader);
        }
        
        leaderIdBox.setModel(model);
    }
    
    public Masterclass getValues() {
        Player selectedLeader = (Player) leaderIdBox.getSelectedItem();
        Masterclass masterclass = new Masterclass();
        masterclass.setLeaderId(selectedLeader.getId());
        masterclass.setMinRating(Integer.parseInt(minRatingField.getText()));
        masterclass.setName(nameField.getText());
        masterclass.setDate(dateField.getText());
        
        return masterclass;
    }
    
    public Masterclass getValues(int id) {
        Player selectedLeader = (Player) leaderIdBox.getSelectedItem();
        Masterclass masterclass = new Masterclass();
        masterclass.setId(id);
        masterclass.setLeaderId(selectedLeader.getId());
        masterclass.setMinRating(Integer.parseInt(minRatingField.getText()));
        masterclass.setName(nameField.getText());
        masterclass.setDate(dateField.getText());
        
        return masterclass;
    }
    
    public void setValues() {
        System.out.println(this.masterclass.getLeaderId());
        leaderIdBox.setSelectedItem(Integer.toString(this.masterclass.getLeaderId()));
        minRatingField.setText(Integer.toString(this.masterclass.getMinRating()));
        nameField.setText(this.masterclass.getName());
        dateField.setText(this.masterclass.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minRatingField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameValidationLabel = new javax.swing.JLabel();
        dateValidationLabel = new javax.swing.JLabel();
        minRatingValidationLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        leaderIdBox = new javax.swing.JComboBox();

        jLabel1.setText("Naam");

        jLabel2.setText("Datum");

        jLabel3.setText("Min rating");

        jLabel7.setText("(dd-mm-jjjj uu:mm)");

        jLabel4.setText("Gegeven door");

        leaderIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderIdBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(dateField)
                    .addComponent(minRatingField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(leaderIdBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addComponent(nameValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minRatingValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(minRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRatingValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leaderIdBox)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void leaderIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderIdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderIdBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField dateField;
    public javax.swing.JLabel dateValidationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JComboBox leaderIdBox;
    public javax.swing.JTextField minRatingField;
    public javax.swing.JLabel minRatingValidationLabel;
    public javax.swing.JTextField nameField;
    public javax.swing.JLabel nameValidationLabel;
    // End of variables declaration//GEN-END:variables
}
