/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.masterclass;

import fullhouse.Panel;
import fullhouse.exceptions.FormValidationException;
import fullhouse.models.Masterclass;
import fullhouse.repositories.MasterclassDbRepository;
import fullhouse.validation.MasterclassValidator;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author steve
 */
public class MasterclassPanel extends javax.swing.JPanel {
    private MasterclassDbRepository repository = new MasterclassDbRepository();
    private Panel panel = new Panel();
    private String action;
    private Masterclass masterclass;
    /**
     * Creates new form MasterClassPanel
     */
    public MasterclassPanel() {
        initComponents();
        
        panel.initializeButtons(
                new javax.swing.JButton[] { addMasterclassButton, editMasterclassButton, deleteMasterclassButton },
                new javax.swing.JButton[] { cancelMasterclassButton, saveMasterclassButton }    
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelMasterclassButton = new javax.swing.JButton();
        deleteMasterclassButton = new javax.swing.JButton();
        addMasterclassButton = new javax.swing.JButton();
        editMasterclassButton = new javax.swing.JButton();
        saveMasterclassButton = new javax.swing.JButton();
        subPanel = new javax.swing.JPanel();

        cancelMasterclassButton.setText("Annuleer");
        cancelMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMasterclassButtonActionPerformed(evt);
            }
        });

        deleteMasterclassButton.setText("Verwijder class");
        deleteMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMasterclassButtonActionPerformed(evt);
            }
        });

        addMasterclassButton.setText("Voeg class toe");
        addMasterclassButton.setMaximumSize(new java.awt.Dimension(119, 23));
        addMasterclassButton.setMinimumSize(new java.awt.Dimension(119, 23));
        addMasterclassButton.setPreferredSize(new java.awt.Dimension(119, 23));
        addMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMasterclassButtonActionPerformed(evt);
            }
        });

        editMasterclassButton.setText("Wijzig class");
        editMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMasterclassButtonActionPerformed(evt);
            }
        });

        saveMasterclassButton.setText("Opslaan");
        saveMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMasterclassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveMasterclassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelMasterclassButton)
                .addGap(0, 143, Short.MAX_VALUE))
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMasterclassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMasterclassButton)
                    .addComponent(deleteMasterclassButton)
                    .addComponent(saveMasterclassButton)
                    .addComponent(cancelMasterclassButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMasterclassButtonActionPerformed
        this.action = "CREATE";
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterclassFormPanel());
        panel.toForm();
    }//GEN-LAST:event_addMasterclassButtonActionPerformed

    private void editMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMasterclassButtonActionPerformed
        try {
            MasterclassCollectionPanel collection = (MasterclassCollectionPanel) subPanel;
            JTable table = collection.masterclassCollectionTable;
            Masterclass selectedMasterclass = (Masterclass) table.getValueAt(table.getSelectedRow(), 0);

            this.action = "EDIT";
            this.masterclass = selectedMasterclass;

            subPanel = Panel.changeView(this, subPanel, new MasterclassTabsPanel(selectedMasterclass));
            panel.toForm();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(panel, "Selecteer aub een masterclass");
        }
    }//GEN-LAST:event_editMasterclassButtonActionPerformed

    private void saveMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMasterclassButtonActionPerformed
        try {
            MasterclassValidator validator = new MasterclassValidator();

            if (this.action == "CREATE") {
                MasterclassFormPanel form = (MasterclassFormPanel) subPanel;
                validator.validate(form);
                this.repository.add(form.getValues());
            } else if (this.action == "EDIT") {
                MasterclassFormPanel form = (MasterclassFormPanel) MasterclassTabsPanel.selectedComponent;
                validator.validate(form);
                this.repository.update(form.getValues(this.masterclass.getId()));
            }

            subPanel = Panel.changeView(this, subPanel, new MasterclassCollectionPanel());
            panel.toCollection();
        } catch (FormValidationException e) {
            e.setErrors();
        }
    }//GEN-LAST:event_saveMasterclassButtonActionPerformed

    private void cancelMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMasterclassButtonActionPerformed
        subPanel = Panel.changeView(this, subPanel, new fullhouse.modules.masterclass.MasterclassCollectionPanel());
        panel.toCollection();
    }//GEN-LAST:event_cancelMasterclassButtonActionPerformed

    private void deleteMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMasterclassButtonActionPerformed
        try {
            MasterclassCollectionPanel collection = (MasterclassCollectionPanel) subPanel;
            JTable table = collection.masterclassCollectionTable;
            Masterclass selectedMasterclass = (Masterclass) table.getValueAt(table.getSelectedRow(), 0);
            this.repository.delete(selectedMasterclass.getId(), table);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(panel, "Selecteer aub een masterclass");
        }
    }//GEN-LAST:event_deleteMasterclassButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMasterclassButton;
    private javax.swing.JButton cancelMasterclassButton;
    private javax.swing.JButton deleteMasterclassButton;
    private javax.swing.JButton editMasterclassButton;
    private javax.swing.JButton saveMasterclassButton;
    public javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}
