/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.player;

import fullhouse.Panel;
import fullhouse.exceptions.FormValidationException;
import fullhouse.models.Player;
import fullhouse.repositories.PlayerDbRepository;
import fullhouse.validation.PlayerValidator;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Liam Hubers
 */
public class PlayerPanel extends javax.swing.JPanel {

    private PlayerDbRepository repository = new PlayerDbRepository();
    private Panel panel = new Panel();
    private String action;
    private Player player;

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        initComponents();

        panel.initializeButtons(
                new javax.swing.JButton[]{addPlayerButton, editPlayerButton, deletePlayerButton},
                new javax.swing.JButton[]{cancelPlayerButton, savePlayerButton}
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletePlayerButton = new javax.swing.JButton();
        addPlayerButton = new javax.swing.JButton();
        editPlayerButton = new javax.swing.JButton();
        savePlayerButton = new javax.swing.JButton();
        subPanel = new javax.swing.JPanel();
        cancelPlayerButton = new javax.swing.JButton();

        deletePlayerButton.setText("Verwijder speler");
        deletePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlayerButtonActionPerformed(evt);
            }
        });

        addPlayerButton.setText("Voeg speler toe");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        editPlayerButton.setText("Wijzig speler");
        editPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPlayerButtonActionPerformed(evt);
            }
        });

        savePlayerButton.setText("Opslaan");
        savePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        cancelPlayerButton.setText("Annuleer");
        cancelPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePlayerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelPlayerButton)
                .addContainerGap(386, Short.MAX_VALUE))
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerButton)
                    .addComponent(editPlayerButton)
                    .addComponent(deletePlayerButton)
                    .addComponent(savePlayerButton)
                    .addComponent(cancelPlayerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        this.action = "CREATE";
        subPanel = Panel.changeView(this, subPanel, new PlayerFormPanel());
        panel.toForm();
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void savePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlayerButtonActionPerformed
        PlayerFormPanel form = (PlayerFormPanel) subPanel;

        try {
            new PlayerValidator().validate(form);

            if (this.action == "CREATE") {
                this.repository.add(form.getValues());
            } else if (this.action == "EDIT") {
                this.repository.update(form.getValues(this.player.getId()));
            }

            subPanel = Panel.changeView(this, subPanel, new PlayerCollectionPanel());
            panel.toCollection();
        } catch (FormValidationException e) {
            e.setErrors();
        }
    }//GEN-LAST:event_savePlayerButtonActionPerformed

    private void editPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPlayerButtonActionPerformed
        try {
            PlayerCollectionPanel collection = (PlayerCollectionPanel) subPanel;
            JTable table = collection.playerCollectionTable;
            Player selectedPlayer = (Player) table.getValueAt(table.getSelectedRow(), 0);

            this.action = "EDIT";
            this.player = selectedPlayer;

            subPanel = Panel.changeView(this, subPanel, new PlayerFormPanel(selectedPlayer));
            panel.toForm();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(panel, "Selecteer aub een speler");
        }
    }//GEN-LAST:event_editPlayerButtonActionPerformed

    private void deletePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlayerButtonActionPerformed
        try {
            PlayerCollectionPanel collection = (PlayerCollectionPanel) subPanel;
            JTable table = collection.playerCollectionTable;
            Player selectedPlayer = (Player) table.getValueAt(table.getSelectedRow(), 0);
            this.repository.delete(selectedPlayer.getId(), table);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(panel, "Selecteer aub een speler");
        }
    }//GEN-LAST:event_deletePlayerButtonActionPerformed

    private void cancelPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPlayerButtonActionPerformed
        subPanel = Panel.changeView(this, subPanel, new PlayerCollectionPanel());
        panel.toCollection();
    }//GEN-LAST:event_cancelPlayerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JButton cancelPlayerButton;
    private javax.swing.JButton deletePlayerButton;
    private javax.swing.JButton editPlayerButton;
    private javax.swing.JButton savePlayerButton;
    public javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}
