/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fullhouse.frames;

import fullhouse.repositories.PlayerDbRepository;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JPanel;

/**
 *
 * @author Liam Hubers
 */
public class PlayerPanel extends javax.swing.JPanel {
    private Dimension size;
    private Point point;
    private PlayerDbRepository playerRepo = new PlayerDbRepository();

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        initComponents();
        
        playerCancelButton.setVisible(false);
        savePlayerButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletePlayerButton = new javax.swing.JButton();
        addPlayerButton = new javax.swing.JButton();
        editPlayerButton = new javax.swing.JButton();
        savePlayerButton = new javax.swing.JButton();
        playerCancelButton = new javax.swing.JButton();
        subPanel = new javax.swing.JPanel();

        deletePlayerButton.setText("Verwijder speler");

        addPlayerButton.setText("Voeg speler toe");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        editPlayerButton.setText("Wijzig speler");

        savePlayerButton.setText("Opslaan");
        savePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlayerButtonActionPerformed(evt);
            }
        });

        playerCancelButton.setText("Annuleer");

        subPanel.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePlayerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerCancelButton)
                .addContainerGap(386, Short.MAX_VALUE))
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerButton)
                    .addComponent(editPlayerButton)
                    .addComponent(deletePlayerButton)
                    .addComponent(savePlayerButton)
                    .addComponent(playerCancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        changeView(new PlayerFormPanel(playerRepo));
        playerRepo.addPlayer();
        
        addPlayerButton.setVisible(false);
        deletePlayerButton.setVisible(false);
        editPlayerButton.setVisible(false);
        playerCancelButton.setVisible(true);
        savePlayerButton.setVisible(true);
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void savePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlayerButtonActionPerformed
        // TODO add your handling code here:
        changeView(new PlayerCollectionPanel());
        
        addPlayerButton.setVisible(true);
        deletePlayerButton.setVisible(true);
        editPlayerButton.setVisible(true);
        playerCancelButton.setVisible(false);
        savePlayerButton.setVisible(false);
    }//GEN-LAST:event_savePlayerButtonActionPerformed

    public void changeView(javax.swing.JPanel panel)
    {        
        revalidate();
        
        size = subPanel.getSize();
        point = subPanel.getLocation();
        
        remove(subPanel);
        
        subPanel = panel;
        
        add(panel);

        panel.setLocation(point.x, point.y);
        panel.setSize(size.width, size.height);
        
        revalidate();
        validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JButton deletePlayerButton;
    private javax.swing.JButton editPlayerButton;
    private javax.swing.JButton playerCancelButton;
    private javax.swing.JButton savePlayerButton;
    private javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}
