/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fullhouse.modules.tournament;

import javax.swing.JLabel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Guido
 */
public class TournamentCollectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TournamentCollectionPanel
     */
    public TournamentCollectionPanel() {
        initComponents();
        
        TableCellRenderer r = TournamentCollectionTable.getTableHeader().getDefaultRenderer();
        JLabel l = (JLabel) r;
        l.setHorizontalAlignment(JLabel.LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TournamentCollectionTable = new javax.swing.JTable();

        TournamentCollectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Toernooi #1", "Den Haag", "24 december 2014", "37/256", "1000"},
                {"For the noobs #2", "Almere", "29 december 2014", "13/64", "600"},
                {"Toernooi #3", "Eindhoven", "5 januari 2015", "8/32", "800"},
                {"Bazen only #4", "Ypenburg", "19 februari 2015", "1/32", "1600"}
            },
            new String [] {
                "Naam", "Plaats", "Datum", "Aantal spelers (ingeschreven/max)", "Min. ranking"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TournamentCollectionTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TournamentCollectionTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
