/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fullhouse.modules.tournament;

import fullhouse.repositories.TournamentDbRepository;
import javax.swing.JLabel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Guido
 */
public class TournamentCollectionPanel extends javax.swing.JPanel {
    
    private TournamentDbRepository repository = new TournamentDbRepository();
    /**
     * Creates new form TournamentCollectionPanel
     */
    public TournamentCollectionPanel() {
        initComponents();
        
        TableCellRenderer r = tournamentCollectionTable.getTableHeader().getDefaultRenderer();
        JLabel l = (JLabel) r;
        l.setHorizontalAlignment(JLabel.LEFT);
        
        tournamentCollectionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        this.repository.collection(tournamentCollectionTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tournamentCollectionTable = new javax.swing.JTable();

        tournamentCollectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naam", "Plaats", "Datum", "Inschrijvingen(aantal/max)"
            }
        ));
        jScrollPane1.setViewportView(tournamentCollectionTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable tournamentCollectionTable;
    // End of variables declaration//GEN-END:variables
}
