/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse.modules.tournament;

import fullhouse.models.Tournament;
import static fullhouse.modules.masterclass.MasterclassTabsPanel.selectedComponent;
import fullhouse.repositories.TournamentDbRepository;
import java.awt.Component;

/**
 *
 * @author steve
 */
public class TournamentTabsPanel extends javax.swing.JPanel {

    private final TournamentDbRepository repository = new TournamentDbRepository();
    public static Component selectedComponent;

    /**
     * Creates new form TournamentFormPanel
     */
    public TournamentTabsPanel(Tournament tournament) {
        initComponents();

        TournamentFormPanel form = new TournamentFormPanel(tournament);

        boolean test = tournament.isGeneratedRounds();

        tournamentTabs.addTab("Gegevens", form);
        tournamentTabs.addTab("Speler inschrijven", new TournamentSignupPanel(tournament));
        if (test) {
            tournamentTabs.addTab("Tafelindeling", new TournamentTableLayoutCollectionPanel(tournament.getId()));
        } else {
            tournamentTabs.addTab("Tafelindeling", new TournamentTableLayoutPanel(tournament.getId(), form));
        }
        tournamentTabs.addTab("Uitslag", new TournamentResultsPanel(tournament.getId()));
        
        selectedComponent = tournamentTabs.getSelectedComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tournamentTabs = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tournamentTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tournamentTabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tournamentTabs;
    // End of variables declaration//GEN-END:variables
}
